//About models
export const FETCH_POST_DATA = 'FETCH_POST_DATA';
export const FETCH_SINGLE_POST_DATA = 'FETCH_SINGLE_POST_DATA';
export const SET_SINGLE_POST_DATA = 'SET_SINGLE_POST_DATA';
export const FETCH_POST_DATA_SUCCESS = "FETCH_POST_DATA_SUCCESS";
export const FETCH_POST_DATA_ERROR = "FETCH_POST_DATA_ERROR";
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const FETCH_BEST_POSTS = 'FETCH_BEST_POSTS';
export const FETCH_PREMIUM_MODELS = 'FETCH_PREMIUM_MODELS';



//About reviews
export const FETCH_POST_REVIEWS = 'FETCH_POST_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';


//ERROR HANDLING
export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

//SHOWING MODALS
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

//GENERAL LOADING FLAG
export const IS_LOADING = 'IS_LOADING';
export const IS_NOT_LOADING = 'IS_NOT_LOADING';

//SHOWING GUYS OR GIRLS
export const SET_SHOW = 'SET_SHOW';